### PR TITLE
Using whitelist .npmignore

### LINKED ISSUE #14: invalid package.json files in .history breaks flow type checker
flow type checks json files under node_modules by default

The following json files are invalid causing flow to fail:

- node_modules/yarn/deduplicate/.history/package_20181018055733.json:
- node_modules/yarn-deduplicate/.history/package_20181018055741.json

Can we remove/fix these files?

Steps to reproduce:
````
$ yarn flow check

Error -----------------------------------------node_modules/yarn/deduplicate/.history/package_20181018055733.json:41:3

Unexpected token }

   41|   }
         ^


Error ------------------------------------------ node_modules/yarn-deduplicate/.history/package_20181018055741.json:41:3

Unexpected token }

   41|   }
         ^
```

### PR DESCRIPTION
**Pull request by felipemsantana**
Closes #14 by using whitelist for `.npmignore` instead of blacklist.

### Before
```
npm notice
npm notice 📦  yarn-deduplicate@1.0.0
npm notice === Tarball Contents ===
npm notice 968B   package.json
npm notice 1B     .nvmrc
npm notice 268B   AUTHORS
npm notice 1.3kB  CHANGELOG.md
npm notice 1.6kB  cli.js
npm notice 2.5kB  CODE_OF_CONDUCT.md
npm notice 5.2kB  index.js
npm notice 11.4kB LICENSE.txt
npm notice 6.0kB  README.md
npm notice 85.2kB yarn.lock
npm notice 375B   __fixtures__/yarn.lock
npm notice 2.3kB  __tests__/cli.js
npm notice 4.0kB  __tests__/index.js
npm notice 506B   .circleci/config.yml
npm notice === Tarball Details ===
npm notice name:          yarn-deduplicate
npm notice version:       1.0.0
npm notice filename:      yarn-deduplicate-1.0.0.tgz
npm notice package size:  37.0 kB
npm notice unpacked size: 121.5 kB
npm notice shasum:        924f2beb68f1fc9457b46bd26bd2ca9411e25fd5
npm notice integrity:     sha512-48k+q+YrFG2HI[...]Y1movsAxf54uQ==
npm notice total files:   14
npm notice
yarn-deduplicate-1.0.0.tgz
```

### After
```
npm notice
npm notice 📦  yarn-deduplicate@1.0.0
npm notice === Tarball Contents ===
npm notice 968B   package.json
npm notice 1.3kB  CHANGELOG.md
npm notice 1.6kB  cli.js
npm notice 5.2kB  index.js
npm notice 11.4kB LICENSE.txt
npm notice 6.0kB  README.md
npm notice === Tarball Details ===
npm notice name:          yarn-deduplicate
npm notice version:       1.0.0
npm notice filename:      yarn-deduplicate-1.0.0.tgz
npm notice package size:  9.4 kB
npm notice unpacked size: 26.3 kB
npm notice shasum:        68726534c30c6d77b64428ac010b87d24a6cd0f7
npm notice integrity:     sha512-dtasN+5pjILjx[...]2qjI6+OJdQ5qQ==
npm notice total files:   6
npm notice
yarn-deduplicate-1.0.0.tgz
```

### CODE REVIEW

**Comment by felipemsantana** [comment]
Includes a bonus: faster install size :stuck_out_tongue:

**Comment by rye** [comment]
@felipemsantana, I like this fix, but it might be a bit excessive to resolve the underlying problem, couldn't we just ignore `/.history/` to resolve #14?  Otherwise, we're ignoring all the other files, like `AUTHORS`, `CHANGELOG.md`, and (perhaps most importantly) `LICENSE.md`.

Would you agree?  For what it's worth, the only files I really think really should be ignored are in .history—most of the node modules I've seen include the extra files.

```console
$ wget "https://registry.yarnpkg.com/yarn-deduplicate/-/yarn-deduplicate-1.0.0.tgz"
$ tar tvzf yarn-deduplicate-1.0.0.tgz
drwxr-xr-x  0 0      0           0 Oct 30 23:56 package
drwxr-xr-x  0 0      0           0 Oct 30 23:54 package/.circleci
drwxr-xr-x  0 0      0           0 Oct 31 00:39 package/.history
-rw-r--r--  0 0      0           1 Oct 30 23:54 package/.nvmrc
-rw-r--r--  0 0      0         268 Oct 30 23:54 package/AUTHORS
-rw-r--r--  0 0      0        1367 Oct 31 00:35 package/CHANGELOG.md
-rw-r--r--  0 0      0        2480 Jun 16 22:16 package/CODE_OF_CONDUCT.md
-rw-r--r--  0 0      0       11357 Jun 16 22:16 package/LICENSE.txt
-rw-r--r--  0 0      0        5983 Oct 31 00:38 package/README.md
drwxr-xr-x  0 0      0           0 Oct 30 23:54 package/__fixtures__
drwxr-xr-x  0 0      0           0 Oct 30 23:54 package/__tests__
-rwxr-xr-x  0 0      0        1562 Oct 31 00:36 package/cli.js
-rw-r--r--  0 0      0        5160 Oct 30 23:54 package/index.js
-rw-r--r--  0 0      0         968 Oct 31 00:41 package/package.json
-rw-r--r--  0 0      0         506 Oct 30 23:54 package/.circleci/config.yml
drwxr-xr-x  0 0      0           0 Oct 30 00:39 package/.history/.circleci
-rw-r--r--  0 0      0        1571 Oct 29 00:31 package/.history/.gitignore_20180617140434
-rw-r--r--  0 0      0        1579 Oct 29 00:31 package/.history/.gitignore_20181029163154
-rw-r--r--  0 0      0           0 Oct 30 00:38 package/.history/.nvmrc_20181030163811
-rw-r--r--  0 0      0           1 Oct 30 00:38 package/.history/.nvmrc_20181030163823
-rw-r--r--  0 0      0         268 Oct 30 00:15 package/.history/AUTHORS_20181030161525
-rw-r--r--  0 0      0         683 Oct 30 00:34 package/.history/CHANGELOG_20181029164642.md
-rw-r--r--  0 0      0        1295 Oct 30 00:34 package/.history/CHANGELOG_20181030163436.md
-rw-r--r--  0 0      0        1367 Oct 31 00:35 package/.history/CHANGELOG_20181031163556.md
-rw-r--r--  0 0      0        5204 Oct 17 13:22 package/.history/README_20181018052254.md
-rw-r--r--  0 0      0        5928 Oct 30 00:33 package/.history/README_20181030163358.md
-rw-r--r--  0 0      0        5946 Oct 30 23:58 package/.history/README_20181031155813.md
-rw-r--r--  0 0      0        5938 Oct 30 23:59 package/.history/README_20181031155906.md
-rw-r--r--  0 0      0        5946 Oct 31 00:31 package/.history/README_20181031163142.md
-rw-r--r--  0 0      0        6062 Oct 31 00:37 package/.history/README_20181031163703.md
-rw-r--r--  0 0      0        6064 Oct 31 00:37 package/.history/README_20181031163709.md
-rw-r--r--  0 0      0        6069 Oct 31 00:37 package/.history/README_20181031163741.md
-rw-r--r--  0 0      0        6074 Oct 31 00:37 package/.history/README_20181031163749.md
-rw-r--r--  0 0      0        5973 Oct 31 00:38 package/.history/README_20181031163802.md
-rw-r--r--  0 0      0        5983 Oct 31 00:38 package/.history/README_20181031163807.md
drwxr-xr-x  0 0      0           0 Oct 30 00:36 package/.history/__tests__
-rw-r--r--  0 0      0        1268 Oct 17 13:18 package/.history/cli_20181018051831.js
-rw-r--r--  0 0      0        1278 Oct 17 13:24 package/.history/cli_20181018052407.js
-rw-r--r--  0 0      0        1275 Oct 17 13:27 package/.history/cli_20181018052714.js
-rw-r--r--  0 0      0        1287 Oct 17 13:31 package/.history/cli_20181018053121.js
-rw-r--r--  0 0      0        1289 Oct 17 13:31 package/.history/cli_20181018053123.js
-rw-r--r--  0 0      0        1465 Oct 17 13:39 package/.history/cli_20181018053951.js
-rw-r--r--  0 0      0        1464 Oct 17 13:39 package/.history/cli_20181018053953.js
-rw-r--r--  0 0      0        1526 Oct 17 13:40 package/.history/cli_20181018054028.js
-rw-r--r--  0 0      0        1527 Oct 17 13:40 package/.history/cli_20181018054030.js
-rw-r--r--  0 0      0        1532 Oct 17 13:41 package/.history/cli_20181018054129.js
-rw-r--r--  0 0      0        1522 Oct 29 00:18 package/.history/cli_20181029161821.js
-rw-r--r--  0 0      0        1532 Oct 29 00:18 package/.history/cli_20181029161836.js
-rw-r--r--  0 0      0        1530 Oct 29 00:18 package/.history/cli_20181029161853.js
-rw-r--r--  0 0      0        1558 Oct 29 00:19 package/.history/cli_20181029161953.js
-rw-r--r--  0 0      0        1557 Oct 29 00:19 package/.history/cli_20181029161955.js
-rw-r--r--  0 0      0        1550 Oct 29 00:20 package/.history/cli_20181029162035.js
-rw-r--r--  0 0      0        1551 Oct 29 00:20 package/.history/cli_20181029162049.js
-rw-r--r--  0 0      0        1551 Oct 30 23:52 package/.history/cli_20181031155216.js
-rw-r--r--  0 0      0        1552 Oct 30 23:52 package/.history/cli_20181031155255.js
-rw-r--r--  0 0      0        1562 Oct 31 00:36 package/.history/cli_20181031163611.js
-rw-r--r--  0 0      0        3172 Oct 17 13:28 package/.history/index_20180617220636.js
-rw-r--r--  0 0      0        3104 Oct 17 13:28 package/.history/index_20181018052841.js
-rw-r--r--  0 0      0        3117 Oct 17 13:31 package/.history/index_20181018053112.js
-rw-r--r--  0 0      0        3119 Oct 17 13:31 package/.history/index_20181018053131.js
-rw-r--r--  0 0      0        3176 Oct 17 13:32 package/.history/index_20181018053254.js
-rw-r--r--  0 0      0        3172 Oct 17 13:33 package/.history/index_20181018053311.js
-rw-r--r--  0 0      0        3172 Oct 17 13:33 package/.history/index_20181018053314.js
-rw-r--r--  0 0      0        3172 Oct 17 13:33 package/.history/index_20181018053329.js
-rw-r--r--  0 0      0        3232 Oct 17 13:33 package/.history/index_20181018053357.js
-rw-r--r--  0 0      0        3275 Oct 17 13:34 package/.history/index_20181018053413.js
-rw-r--r--  0 0      0        3894 Oct 17 13:35 package/.history/index_20181018053524.js
-rw-r--r--  0 0      0        3937 Oct 17 13:35 package/.history/index_20181018053538.js
-rw-r--r--  0 0      0        3929 Oct 17 13:36 package/.history/index_20181018053608.js
-rw-r--r--  0 0      0        5966 Oct 17 13:39 package/.history/index_20181018053911.js
-rw-r--r--  0 0      0        5958 Oct 17 13:41 package/.history/index_20181018054103.js
-rw-r--r--  0 0      0        5960 Oct 17 13:41 package/.history/index_20181018054106.js
-rw-r--r--  0 0      0        5959 Oct 17 13:41 package/.history/index_20181018054115.js
-rw-r--r--  0 0      0        6016 Oct 17 13:41 package/.history/index_20181018054153.js
-rw-r--r--  0 0      0        6111 Oct 17 13:42 package/.history/index_20181018054219.js
-rw-r--r--  0 0      0        6106 Oct 17 13:42 package/.history/index_20181018054232.js
-rw-r--r--  0 0      0        6133 Oct 17 13:44 package/.history/index_20181018054457.js
-rw-r--r--  0 0      0        6388 Oct 17 13:48 package/.history/index_20181018054807.js
-rw-r--r--  0 0      0        6389 Oct 17 13:48 package/.history/index_20181018054809.js
-rw-r--r--  0 0      0        6323 Oct 17 13:48 package/.history/index_20181018054811.js
-rw-r--r--  0 0      0        6323 Oct 17 13:48 package/.history/index_20181018054834.js
-rw-r--r--  0 0      0        6296 Oct 17 13:48 package/.history/index_20181018054840.js
-rw-r--r--  0 0      0        6481 Oct 17 13:49 package/.history/index_20181018054908.js
-rw-r--r--  0 0      0        6632 Oct 17 13:50 package/.history/index_20181018055017.js
-rw-r--r--  0 0      0        6903 Oct 17 14:14 package/.history/index_20181018061400.js
-rw-r--r--  0 0      0        6903 Oct 28 23:37 package/.history/index_20181029153743.js
-rw-r--r--  0 0      0        7368 Oct 28 23:38 package/.history/index_20181029153853.js
-rw-r--r--  0 0      0        6900 Oct 28 23:39 package/.history/index_20181029153921.js
-rw-r--r--  0 0      0        6992 Oct 28 23:41 package/.history/index_20181029154153.js
-rw-r--r--  0 0      0        7796 Oct 28 23:45 package/.history/index_20181029154519.js
-rw-r--r--  0 0      0        7272 Oct 28 23:48 package/.history/index_20181029154845.js
-rw-r--r--  0 0      0        7272 Oct 28 23:48 package/.history/index_20181029154857.js
-rw-r--r--  0 0      0        7334 Oct 28 23:50 package/.history/index_20181029155007.js
-rw-r--r--  0 0      0        7391 Oct 28 23:50 package/.history/index_20181029155020.js
-rw-r--r--  0 0      0        7406 Oct 28 23:50 package/.history/index_20181029155029.js
-rw-r--r--  0 0      0        7402 Oct 28 23:50 package/.history/index_20181029155049.js
-rw-r--r--  0 0      0        7379 Oct 28 23:51 package/.history/index_20181029155130.js
-rw-r--r--  0 0      0        7379 Oct 28 23:51 package/.history/index_20181029155148.js
-rw-r--r--  0 0      0        7374 Oct 28 23:52 package/.history/index_20181029155226.js
-rw-r--r--  0 0      0        7397 Oct 28 23:53 package/.history/index_20181029155326.js
-rw-r--r--  0 0      0        7234 Oct 28 23:53 package/.history/index_20181029155335.js
-rw-r--r--  0 0      0        7236 Oct 28 23:53 package/.history/index_20181029155346.js
-rw-r--r--  0 0      0        7236 Oct 28 23:53 package/.history/index_20181029155352.js
-rw-r--r--  0 0      0        7267 Oct 28 23:56 package/.history/index_20181029155622.js
-rw-r--r--  0 0      0        7267 Oct 28 23:56 package/.history/index_20181029155624.js
-rw-r--r--  0 0      0        6931 Oct 28 23:56 package/.history/index_20181029155632.js
-rw-r--r--  0 0      0        6947 Oct 28 23:57 package/.history/index_20181029155719.js
-rw-r--r--  0 0      0        6947 Oct 28 23:57 package/.history/index_20181029155721.js
-rw-r--r--  0 0      0        6963 Oct 28 23:57 package/.history/index_20181029155738.js
-rw-r--r--  0 0      0        6963 Oct 28 23:58 package/.history/index_20181029155801.js
-rw-r--r--  0 0      0        7241 Oct 28 23:59 package/.history/index_20181029155920.js
-rw-r--r--  0 0      0        7077 Oct 28 23:59 package/.history/index_20181029155949.js
-rw-r--r--  0 0      0        7145 Oct 28 23:59 package/.history/index_20181029155958.js
-rw-r--r--  0 0      0        7162 Oct 29 00:00 package/.history/index_20181029160007.js
-rw-r--r--  0 0      0        6946 Oct 29 00:00 package/.history/index_20181029160011.js
-rw-r--r--  0 0      0        6944 Oct 29 00:01 package/.history/index_20181029160146.js
-rw-r--r--  0 0      0        4826 Oct 29 00:02 package/.history/index_20181029160246.js
-rw-r--r--  0 0      0        4819 Oct 29 00:02 package/.history/index_20181029160257.js
-rw-r--r--  0 0      0        4864 Oct 29 00:04 package/.history/index_20181029160422.js
-rw-r--r--  0 0      0        4983 Oct 29 00:04 package/.history/index_20181029160448.js
-rw-r--r--  0 0      0        5131 Oct 29 00:05 package/.history/index_20181029160514.js
-rw-r--r--  0 0      0        5137 Oct 29 00:05 package/.history/index_20181029160518.js
-rw-r--r--  0 0      0        4985 Oct 29 00:05 package/.history/index_20181029160532.js
-rw-r--r--  0 0      0        5002 Oct 29 00:05 package/.history/index_20181029160542.js
-rw-r--r--  0 0      0        4840 Oct 29 00:06 package/.history/index_20181029160604.js
-rw-r--r--  0 0      0        4856 Oct 29 00:08 package/.history/index_20181029160835.js
-rw-r--r--  0 0      0        4844 Oct 29 00:08 package/.history/index_20181029160857.js
-rw-r--r--  0 0      0        4833 Oct 29 00:09 package/.history/index_20181029160904.js
-rw-r--r--  0 0      0        4811 Oct 29 00:09 package/.history/index_20181029160920.js
-rw-r--r--  0 0      0        4817 Oct 29 00:09 package/.history/index_20181029160924.js
-rw-r--r--  0 0      0        4816 Oct 29 00:09 package/.history/index_20181029160926.js
-rw-r--r--  0 0      0        4776 Oct 29 00:09 package/.history/index_20181029160950.js
-rw-r--r--  0 0      0        4819 Oct 29 00:10 package/.history/index_20181029161006.js
-rw-r--r--  0 0      0        4852 Oct 29 00:10 package/.history/index_20181029161030.js
-rw-r--r--  0 0      0        4857 Oct 29 00:10 package/.history/index_20181029161035.js
-rw-r--r--  0 0      0        4852 Oct 29 00:10 package/.history/index_20181029161039.js
-rw-r--r--  0 0      0        4870 Oct 29 00:10 package/.history/index_20181029161054.js
-rw-r--r--  0 0      0        5158 Oct 29 00:13 package/.history/index_20181029161348.js
-rw-r--r--  0 0      0        4962 Oct 29 00:14 package/.history/index_20181029161410.js
-rw-r--r--  0 0      0        4996 Oct 29 00:14 package/.history/index_20181029161421.js
-rw-r--r--  0 0      0        4834 Oct 29 00:14 package/.history/index_20181029161439.js
-rw-r--r--  0 0      0        4785 Oct 29 00:14 package/.history/index_20181029161446.js
-rw-r--r--  0 0      0        4787 Oct 29 00:14 package/.history/index_20181029161450.js
-rw-r--r--  0 0      0        4829 Oct 29 00:14 package/.history/index_20181029161454.js
-rw-r--r--  0 0      0        4916 Oct 29 00:15 package/.history/index_20181029161525.js
-rw-r--r--  0 0      0        4946 Oct 29 00:15 package/.history/index_20181029161537.js
-rw-r--r--  0 0      0        4723 Oct 29 00:15 package/.history/index_20181029161546.js
-rw-r--r--  0 0      0        4723 Oct 29 00:16 package/.history/index_20181029161640.js
-rw-r--r--  0 0      0        4740 Oct 29 00:16 package/.history/index_20181029161644.js
-rw-r--r--  0 0      0        4740 Oct 29 00:16 package/.history/index_20181029161649.js
-rw-r--r--  0 0      0        4757 Oct 29 00:16 package/.history/index_20181029161653.js
-rw-r--r--  0 0      0        4739 Oct 29 00:17 package/.history/index_20181029161709.js
-rw-r--r--  0 0      0        4749 Oct 29 00:17 package/.history/index_20181029161712.js
-rw-r--r--  0 0      0        4859 Oct 29 00:28 package/.history/index_20181029162816.js
-rw-r--r--  0 0      0        4877 Oct 29 00:28 package/.history/index_20181029162822.js
-rw-r--r--  0 0      0        5069 Oct 29 00:28 package/.history/index_20181029162836.js
-rw-r--r--  0 0      0        5044 Oct 29 01:12 package/.history/index_20181029171208.js
-rw-r--r--  0 0      0        5150 Oct 29 01:45 package/.history/index_20181029174532.js
-rw-r--r--  0 0      0        5105 Oct 29 01:45 package/.history/index_20181029174539.js
-rw-r--r--  0 0      0        5110 Oct 29 01:46 package/.history/index_20181029174625.js
-rw-r--r--  0 0      0        5160 Oct 29 01:46 package/.history/index_20181029174638.js
-rw-r--r--  0 0      0         874 Oct 17 13:57 package/.history/package_20181018055733.json
-rw-r--r--  0 0      0         859 Oct 17 13:57 package/.history/package_20181018055741.json
-rw-r--r--  0 0      0         858 Oct 17 13:57 package/.history/package_20181018055744.json
-rw-r--r--  0 0      0         902 Oct 17 13:59 package/.history/package_20181018055934.json
-rw-r--r--  0 0      0         902 Oct 30 00:38 package/.history/package_20181030163852.json
-rw-r--r--  0 0      0         925 Oct 31 00:33 package/.history/package_20181031163353.json
-rw-r--r--  0 0      0         940 Oct 31 00:36 package/.history/package_20181031163628.json
-rw-r--r--  0 0      0         945 Oct 31 00:36 package/.history/package_20181031163634.json
-rw-r--r--  0 0      0         950 Oct 31 00:39 package/.history/package_20181031163948.json
-rw-r--r--  0 0      0        2260 Oct 30 23:54 package/__tests__/cli.js
-rw-r--r--  0 0      0        4045 Oct 30 23:54 package/__tests__/index.js
-rw-r--r--  0 0      0         509 Oct 30 00:39 package/.history/.circleci/config_20181029164642.yml
-rw-r--r--  0 0      0         506 Oct 30 00:39 package/.history/.circleci/config_20181030163952.yml
-rw-r--r--  0 0      0        2260 Oct 30 00:36 package/.history/__tests__/cli_20181030161413.js
-rw-r--r--  0 0      0        2402 Oct 17 13:31 package/.history/__tests__/index_20180617221510.js
-rw-r--r--  0 0      0        2416 Oct 17 13:31 package/.history/__tests__/index_20181018053138.js
-rw-r--r--  0 0      0        3076 Oct 17 13:53 package/.history/__tests__/index_20181018055308.js
-rw-r--r--  0 0      0        2868 Oct 17 13:53 package/.history/__tests__/index_20181018055330.js
-rw-r--r--  0 0      0        2868 Oct 17 13:53 package/.history/__tests__/index_20181018055347.js
-rw-r--r--  0 0      0        2939 Oct 17 13:54 package/.history/__tests__/index_20181018055426.js
-rw-r--r--  0 0      0        3034 Oct 17 13:54 package/.history/__tests__/index_20181018055438.js
-rw-r--r--  0 0      0        3031 Oct 17 13:54 package/.history/__tests__/index_20181018055452.js
-rw-r--r--  0 0      0        2650 Oct 17 14:00 package/.history/__tests__/index_20181018060002.js
-rw-r--r--  0 0      0        2886 Oct 17 14:01 package/.history/__tests__/index_20181018060111.js
-rw-r--r--  0 0      0        2886 Oct 17 14:01 package/.history/__tests__/index_20181018060120.js
-rw-r--r--  0 0      0        2907 Oct 17 14:01 package/.history/__tests__/index_20181018060125.js
-rw-r--r--  0 0      0        2940 Oct 17 14:01 package/.history/__tests__/index_20181018060148.js
-rw-r--r--  0 0      0        2939 Oct 17 14:01 package/.history/__tests__/index_20181018060151.js
-rw-r--r--  0 0      0        2918 Oct 17 14:02 package/.history/__tests__/index_20181018060204.js
-rw-r--r--  0 0      0        3201 Oct 17 14:02 package/.history/__tests__/index_20181018060221.js
-rw-r--r--  0 0      0        3111 Oct 17 14:02 package/.history/__tests__/index_20181018060258.js
-rw-r--r--  0 0      0        3165 Oct 17 14:03 package/.history/__tests__/index_20181018060316.js
-rw-r--r--  0 0      0        3166 Oct 17 14:03 package/.history/__tests__/index_20181018060317.js
-rw-r--r--  0 0      0        3167 Oct 17 14:03 package/.history/__tests__/index_20181018060319.js
-rw-r--r--  0 0      0        3188 Oct 17 14:03 package/.history/__tests__/index_20181018060326.js
-rw-r--r--  0 0      0        3186 Oct 17 14:04 package/.history/__tests__/index_20181018060417.js
-rw-r--r--  0 0      0        3174 Oct 17 14:04 package/.history/__tests__/index_20181018060424.js
-rw-r--r--  0 0      0        3177 Oct 17 14:04 package/.history/__tests__/index_20181018060427.js
-rw-r--r--  0 0      0        3174 Oct 17 14:04 package/.history/__tests__/index_20181018060429.js
-rw-r--r--  0 0      0        3196 Oct 17 14:05 package/.history/__tests__/index_20181018060530.js
-rw-r--r--  0 0      0        3197 Oct 17 14:05 package/.history/__tests__/index_20181018060532.js
-rw-r--r--  0 0      0        3197 Oct 17 14:05 package/.history/__tests__/index_20181018060542.js
-rw-r--r--  0 0      0        3197 Oct 17 14:05 package/.history/__tests__/index_20181018060557.js
-rw-r--r--  0 0      0        3199 Oct 17 14:06 package/.history/__tests__/index_20181018060608.js
-rw-r--r--  0 0      0        3195 Oct 17 14:06 package/.history/__tests__/index_20181018060611.js
-rw-r--r--  0 0      0        3165 Oct 17 14:11 package/.history/__tests__/index_20181018061144.js
-rw-r--r--  0 0      0        3165 Oct 17 14:11 package/.history/__tests__/index_20181018061146.js
-rw-r--r--  0 0      0        3164 Oct 17 14:11 package/.history/__tests__/index_20181018061148.js
-rw-r--r--  0 0      0        3143 Oct 17 14:11 package/.history/__tests__/index_20181018061150.js
-rw-r--r--  0 0      0        3921 Oct 29 00:50 package/.history/__tests__/index_20181029165044.js
-rw-r--r--  0 0      0        3920 Oct 29 00:50 package/.history/__tests__/index_20181029165054.js
-rw-r--r--  0 0      0        4013 Oct 29 00:51 package/.history/__tests__/index_20181029165137.js
-rw-r--r--  0 0      0        4013 Oct 29 00:51 package/.history/__tests__/index_20181029165145.js
-rw-r--r--  0 0      0        4013 Oct 29 00:51 package/.history/__tests__/index_20181029165147.js
-rw-r--r--  0 0      0        4014 Oct 29 00:52 package/.history/__tests__/index_20181029165216.js
-rw-r--r--  0 0      0        4015 Oct 29 00:52 package/.history/__tests__/index_20181029165230.js
-rw-r--r--  0 0      0        4012 Oct 29 00:52 package/.history/__tests__/index_20181029165241.js
-rw-r--r--  0 0      0        4013 Oct 29 00:53 package/.history/__tests__/index_20181029165311.js
-rw-r--r--  0 0      0        4012 Oct 29 00:53 package/.history/__tests__/index_20181029165342.js
-rw-r--r--  0 0      0        4013 Oct 29 00:53 package/.history/__tests__/index_20181029165353.js
-rw-r--r--  0 0      0        4015 Oct 29 00:54 package/.history/__tests__/index_20181029165404.js
-rw-r--r--  0 0      0        4070 Oct 29 00:54 package/.history/__tests__/index_20181029165439.js
-rw-r--r--  0 0      0        4072 Oct 29 00:54 package/.history/__tests__/index_20181029165444.js
-rw-r--r--  0 0      0        4045 Oct 29 00:55 package/.history/__tests__/index_20181029165502.js
```

**Comment by scinos** [comment]
🤦‍♂️ 
Sorry, I screw up the packaging. `.history` should never be part of the package.

+1 to whitelist `.js`, instead of blacklist `.history`. There is no reason to include tests in the package, for example (specially if in the future we add a few example yarn.lock for common projects to test "advanced" scenarios, for example).

**Comment by scinos** [comment]
Thanks for fixing this @felipemsantana and everybody that participated in this PR.

**Pull request merged**
